const button = document.querySelector('.showme')
console.log(button)
const h1Id = document.querySelector('#pillado')
console.log(h1Id)
const allsP = document.querySelectorAll('p')
console.log(allsP)
const allsMyH4 = document.querySelectorAll('.pokemon')
console.log(allsMyH4)
const allsAttribute = document.querySelectorAll('span[data-function="testMe"]')
console.log(allsAttribute)
